### ISSUE TITLE
preselected = 1 in own group

### ISSUE THREAD

**Issue by format-gmbh** [dmind-gmbh/extension-cookieman#125]
# Pre-selection of an own group not possible

## Prerequisites

* TYPO3 v9.5.15
* EXT:cookieman 2.4.4

## Description
TS: plugin.tx_cookieman.settings.groups.statistik.preselected = 1
With this setting I cannot achieve that the group statistik is pre-selected.

**Comment by jonaseberle** [comment]
It should not make any difference if it is a custom group.

I just checked on the demo page http://cookieman.d-mind.de/theme-bootstrap4-modal and it works for me.

Please check your actual TypoScript in the TypoScript object browser:

![image](https://user-images.githubusercontent.com/1678001/78880603-ef128a80-7a55-11ea-9d66-470aafc8c8e8.png)

Also make sure to reload your browser with CTRL+F5 as else it will try to fill out any form with values that were set before the reload. To be sure, you can navigate to other pages instead of reload.

**Comment by jonaseberle** [comment]
I just saw that we do not have acceptance tests for 'predefined' yet https://github.com/dmind-gmbh/extension-cookieman/blob/master/Tests/Acceptance/Frontend/PopupInteractionsCest.php 
Which we definitely should have ;)

**Comment by format-gmbh** [comment]
With me it looks like this:


![github2](https://user-images.githubusercontent.com/4244457/78887116-99db7680-7a5f-11ea-88f0-d350cd846cc3.png)

**Comment by jonaseberle** [comment]
Looks good. 

Maybe it is related to https://github.com/dmind-gmbh/extension-cookieman/issues/85, but that was fixed and it is in the latest version (which you have).

**Comment by format-gmbh** [comment]
I tested a little more: 
When I restart Firefox, the default setting of the group "Statistik" (without cookie "CookieConsent") is correct. If I then save without the "Statistik" group, then delete the cookie "CookieConsent" and reload Firefox with F5, then the default setting of the "Statistik" group is not correct.  Only when I reload with Strg+F5, the default settings are correct.

**Comment by jonaseberle** [comment]
Yes, that is expected like that.

Andreas Kessel <notifications@github.com> schrieb am Do., 9. Apr. 2020,
17:58:

**Comment by format-gmbh** [comment]
Thank you for your time and effort.
