### ISSUE TITLE
Add a clearly labelled "decline" button to the default themes

### ISSUE THREAD

**Issue by jonaseberle** [dmind-gmbh/extension-cookieman#132]
# Feature Request

**Is your feature request related to a problem? Please describe.**
We have had the request from client's Data Officers to provide a clearly labeled "decline" option. 

Currently we have the buttons save/save all where it might be unclear that "save" means "decline" in the default state.

**Describe the solution you'd like**
It is already possible to use `data-cookieman-accept-none` in custom templates. It should be included in the default themes, though.

When "decline" is the same as "save" (this is the initial state), "save" should not be shown for UX reasons.
The condition could be "show 'save button' if a) the current state is not either 'all cookies' or 'none' or b) after any changes have been done in the current modal".

**Describe alternatives you've considered**
It is already possible to use `<button data-cookieman-accept-none data-cookieman-save>` in custom templates. It should be included in the default themes, though.

**Additional context**
Current clarifications of the European Data Protection Board: https://edpb.europa.eu/sites/edpb/files/files/file1/edpb_guidelines_202005_consent_en.pdf

**Comment by nbiwki** [comment]
Our lawyer has described this problem in the same way. We have already renamed the button to "Reject", but unfortunately this has the effect that if you change the entries or edit them afterwards, you will also have the "Reject" button, although you would prefer the "Save" button at this point.

**Comment by jonaseberle** [comment]
Hi Nico, 

the "reject" button should have `data-cookieman-accept-none data-cooieman-save`. I suggest to add this button instead of renaming the "save" button. 

What I am planning for the default templates would be a logic that shows/hides buttons depending on the current selection.

Do you have a suggestion when each button should be shown?

**Comment by nbiwki** [comment]
Hello,

thanks for the tip with data-cookieman-accept-none.

According to our lawyer, the combination of the save button and expandable settings is problematic. In general it should not be easier to accept all cookies than to reject all unnecessary ones. I know that all non-essential cookies are already deselected in the settings, the customer must first open the settings to check this. As I am writing I am just realizing that it might be a good idea to keep the settings always open.

What would it be like if you made it basically configurable, which button is shown when? There are two states if I have seen it correctly: The first state is when a visitor comes to a website and doesn't have a "CookieConsent" cookie, and the second state is when he already has one and wants to change his decision. In both cases you can decide for yourself if you want to have a save or reject button. It's probably very hard to make a suggestion because the whole cookie thing is legally controversial. Every lawyer has his own interpretation as the relevant laws do not really exist as far as I know.

**Comment by jonaseberle** [comment]
As a first step we could focus on being legally compliant and have 3 buttons:
reject all / save / accept all

I think having the "reject all" (or "decline all" - I'll ask for native speakers in TYPO3 slack #gdpr) is the current requirement. Yet even big cookie consent providers did not implement that yet (E.g. https://borlabs.io/borlabs-cookie/ https://www.cookiebot.com/). https://cookiefirst.com/ on the other hand has it. 

Then we could focus on UX improvements.
The simplest improvement would be to only the "save" button if the selection has changed. We could make it configurable by means of `data-cookieman-*` attributes.

**Comment by jonaseberle** [comment]
I have implemented "Deny all" into the default templates now. 
![image](https://user-images.githubusercontent.com/1678001/84515543-ebf18000-accc-11ea-998c-0d3e7b95d457.png)

I show the "save" button after "settings" have been opened.
![image](https://user-images.githubusercontent.com/1678001/84515729-23f8c300-accd-11ea-8161-715b0d6e4550.png)

That's not the most sophisticated UX, but I was lazy right now... Please reopen the issue if that matters.
