### ISSUE TITLE
don't show mendatory cookies at all

### ISSUE THREAD

**Issue by medarob** [dmind-gmbh/extension-cookieman#181]
Not sure if that is a feature or a bug, so lets see:

I recently attended a privacy / data protection course and one of the topics there was the cookie consent banner.

What I learned: Technically necessary cookies don't need consent from the user. If you set and save an option in a cookie/localstorage and you later use this option so that the website will work correctly, there is no concent necessary. Most of those options are preselected in the mendatory section:

![grafik](https://user-images.githubusercontent.com/33951787/101465256-ffaa3600-393f-11eb-9480-13e95cb31e26.png)

Therefore it's not necessary (or even wrong) to display this mendatory section. It can be left out completely. The user can't change anything and he would give consent to something he can't change.

So, maybe cookieman can be configured that the mendatory cookies are not shown at all with an option like:

`plugin.tx_cookieman.settings.groups.mandatory.hide = 1` ?

**Comment by jonaseberle** [comment]
Sorry for the late reply - I unconsciously deactivated issue watching for the repo.

Yes, we understand the law in the same way: You do not have to show or have consent for necessary 1st party cookies.

Yet we keep it for our customers in order to provide full information to users. But its just a matter of taste.
I'd like to keep it as a default and good starting point.

You can just remove the mandatory group from your groups:

`plugin.tx_cookieman.settings.groups.mandatory >`
