### ISSUE TITLE
Placing Code into <head />

### ISSUE THREAD

**Issue by phoenixh** [dmind-gmbh/extension-cookieman#216]
Hello there,

I am very thankful for the Cookieman Extension and I am using it in different Projects.
Since I need to place the Code of the Google Tag Manager into the <head /> (best would be directly after the opening Tag), I came up with a Feature Request.

Is it possible to implement an Inject Option to place Code into the <head />?

Thank you very much!

**Comment by jonaseberle** [comment]
Hi @phoenixh, 

there are no good reasons to have content put into `<head>` by cookieman. 
Just some of the reasons:
* `<head>` scripts worsen Web Vitals metrics
* Tracking handlers are just fine to be registered later, too since user interaction starts later, too. I am simply ignoring this "best practice" of several tracking mechanisms.
* Since cookieman works by injecting tags when it itself is loaded, putting it to the `<head>` would not have the effect that they want to achieve (being loaded early).

That said, you can change the injection code to put stuff elsewhere. But I don't see any benefit in doing so yet. 

I am open to have a discussion.

**Comment by jonaseberle** [comment]
What do you think @phoenixh ?

**Comment by phoenixh** [comment]
Hello @jonaseberle 

sorry i wasnt replying. 

Now i have another Tracking Service "Hotjar" - the Code needs to be placed in the <head />, otherwise the Code isn't recognized and can be loaded. 

Maybe have a inject Function only for the head would be a good Improvement.

Thank you

**Comment by jonaseberle** [comment]
I doubt that it would make any difference if cookieman would inject into `<head>`. I would rather not add an option for that and complicate things.

You could do that in your `inject` script like so:
```
_script = document.createElement('script')
_script.textContent = 'alert("in <head>")'
document.head.appendChild(_script)
```

**Comment by phoenixh** [comment]
I do understand you, but as long as the Services are not running and the Problem could be in the <head /> I would try to get it sorted with a solution in the <head />.
I will try your code idea and let you know with Feedback on this. 

Thank you

**Comment by jonaseberle** [comment]
@phoenixh could you please give some feedback here?

**Comment by jonaseberle** [comment]
I am closing here.
