### ISSUE TITLE
Missing translation files

### ISSUE THREAD

**Issue by Udo771** [dmind-gmbh/extension-cookieman#224]
# Bug Report

## Prerequisites

TYPO3 v10.4 LTS

## Description

Missing translation files in Resources / Private / Language since version 2.8.2

## Versions

2.8.2 +

**Comment by jonaseberle** [comment]
Why "missing"?

For our v10+ branches we use the TYPO3 translation mechanism for extensions. This allows the translator's community to more easily help with translations.
For branches until v9 we keep the local files since that new TYPO3 translation server was opt-in in TYPO3v9 and our project has never been on the old server.

Have you tried installing translations via https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/Internationalization/ManagingTranslations.html?

**Comment by Udo771** [comment]
ah ok, hatte nicht dran gedacht, danke für den hinweis

**Comment by jonaseberle** [comment]
Ok, tell us please if it works for you.

**Comment by jonaseberle** [comment]
Well, I am closing this.

**Comment by Moongazer** [comment]
Can confirm it works
