### ISSUE TITLE
[FEATURE] Allow adding external scripts (affects strict Content Security Policy)

### ISSUE THREAD

**Issue by sebkln** [dmind-gmbh/extension-cookieman#28]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Websites with the additional HTTP header `Content-Security-Policy` usually **block all inline scripts** in order to prevent XSS attacks. In such an environment, all necessary scripts must be moved to external files (like [Matomo](https://matomo.org/faq/general/faq_20904/)).

The current `inject` solution of EXT:cookieman only supports inline code. External scripts like the following will not be rendered:

    plugin.tx_cookieman.settings.trackingObjects.Matomo {
        inject (
            <script src="https://domain.com/matomo.js" type="text/javascript" async="async"></script>
            <script src="https://domain.com/typo3conf/ext/cookieman_config/Resources/Public/JavaScript/matomo-trackingcode.js" type="text/javascript"></script>
        )
    }

**Describe the solution you'd like**
An approach where you're allowed to add external scripts. I'm not sure how easy that could be accomplished, though.

**Describe alternatives you've considered**
Adding the HTTP header option `'unsafe-inline'` would allow to use EXT:cookieman in environments with `Content-Security-Policy`, but: the protection from cross-site scripting would disappear completely, too.

**Additional context**
I really like your general approach for the Opt-In issue in TYPO3! Currently I'm playing around with this extension, maybe I can come up with some improvements. If you want a `reStructuredText` documentation, I'd gladly send a PR.

Keep up the good work!

**Comment by jonaseberledmind** [comment]
Good point, we did not test with restrictive CSP yet. Thank you for bringing that up. Of course we need to support that.

**Current situation** 
We have some voodoo for `<script>`s in place:
* we let a new DOM-object parse the HTML from the `inject` setting
* with any `<script>` in there (which will be inactive due to being inserted with .innerHTML) we extract it and add it one by one (to the end of the `<body>`)

Here's the relevant section https://github.com/dmind-gmbh/extension-cookieman/blob/0ea02dc4c0c938deb0a3dc2515d3e1fc4447c51f/Resources/Public/Js/cookieman.js#L99-L124

**Found a problem**
I think I just forgot to copy all of the `<script>`'s attributes to the newly inserted one! So e.g. any src= would not be transferred! 
If we do that correctly, I feel we should be ok as we would do then exactly as many tracking objects inject itself: 
<pre>
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</pre>

**Tests**
I'd like to add that also to the automated tests.
Are you using `Content-Security-Policy: script-src 'self'`? 
Thing is that this also affects the example themes: you cannot use `onclick=...` with that ;)

**reSt docs**
Oh, I would be very happy to have the docs .rst'ed and would gladly switch to it:) I just don't have any experience with it yet and feared that our multi-branch-approach would be a bit difiicult to set up with https://docs.typo3.org/ - it would be great if you could get us started with that. Thank you, Sebastian!

**Comment by jonaseberledmind** [comment]
I pushed a JavaScript change that fix inclusion of script tags. 

Could you please review this change in cookieman[.min].js? 

https://github.com/dmind-gmbh/extension-cookieman/commit/b595ae177e7dd20bb862ebf636aa05b25f66b4a5

**Comment by sebkln** [comment]
Great! The external JavaScript sources of my Matomo demo are now injected in the HTML and recognized.

On some pages I now get error messages in the browser console that `_paq.push() was used but Matomo tracker was not initialized before the matomo.js file was loaded.` But this is a different issue that needs to be fixed by myself.

**Comment by jonaseberledmind** [comment]
> On some pages I now get error messages in the browser console that `_paq.push() was used but Matomo tracker was not initialized before the matomo.js file was loaded.` But this is a different issue that needs to be fixed by myself.

Normally you would attach a function to the script like `<script onload="callAllPaq_s()"...>` but as I just learned inline JavaScript wouldn't work with CSP: script-src. 
It would be nice if cookieman could provide an event so that you could do:

    cookieman.TrackingObjects.Matomo.injects.scripts[0].onload = function() { _pag.push() }

That would be possible and not too hard to implement.

**Comment by jonaseberledmind** [comment]
I changed the API a bit from my initial idea: https://github.com/dmind-gmbh/extension-cookieman#cookiemanonscriptloadedstring-trackingobjectkey-int-scriptid-function-callback-void 

Does that fit your use case?
