### ISSUE TITLE
vanilla JavaScript is the future

### ISSUE THREAD

**Issue by ingeniumdesign** [dmind-gmbh/extension-cookieman#328]
Is it possible to reprogram Cookieman without jQuery?
Most of our websites now run without jQuery, as it is no longer up to date.
We only have to load jQuery because of Cookieman.

Plain vanilla JavaScript is the future ;)

**Comment by ToGetATockenOnly** [comment]
https://www.ingeniumdesign.de/ does use jQuery for more that EXT:cookieman , right?

**Comment by ghermens** [comment]
I tend to get rid of jQuery in new projects, too. That doesn't mean **all** my projects are already free of jQuery dependencies ...

**Comment by jonaseberle** [comment]
cookieman does not use jQuery! So we are the future. Closing here.

If you implement your own theme you don't have to use jQuery.

**Comment by ingeniumdesign** [comment]
Okay, jquery is specified in the requirements:

> Requirements
> If you reimplement your own theme, it has no requirements at all
> 
> for the example themes:
> 
> Bootstrap 3/4/5 CSS
> 
> Bootstrap 3/4/5 JavaScript for collapse and modal
> 
> jQuery
> 
> we also apreciate new and creative custom themes

**Comment by jonaseberle** [comment]
I think it should be clear from the docs https://docs.typo3.org/p/dmind/cookieman/main/en-us/Installation/Index.html#requirements that you quoted that it is only for the example Bootstrap themes.

For the [Bootstrap 5 example theme .js](https://github.com/dmind-gmbh/extension-cookieman/blob/master/Resources/Public/Themes/bootstrap4-modal/cookieman-theme.js) that could be rewritten because BS5 does not require jQuery any more. A pull request is welcome.
